name: wall
description: "Anynous chat wall"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1
  flutter: 3.32.6

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0 # Use the latest version
  intl: ^0.20.2 # For date formatting
  logging: ^1.3.0
  shared_preferences: ^2.2.3 # For local storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
