name: wall
description: "Anonymous chat wall"
author: Design Leaders Finland <info@designleaders.fi>
license: Apache-2.0
publish_to: 'none'
version: 0.1.0

homepage: https://wall.designleaders.fi
repository: https://github.com/Design-Leaders-Finland/wall
issue_tracker: https://github.com/Design-Leaders-Finland/wall/issues

environment:
  sdk: ^3.8.1
  flutter: 3.32.6

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1 # Use the latest version
  intl: ^0.20.2 # For date formatting
  logging: ^1.3.0
  shared_preferences: ^2.5.3 # For local storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/certificates/
